[boris]
  version = 1

[build.dist]
  command = [["bin/ci"]]

[build.dist-validate]
  command = [["validate-respect"]]

[build.all-rebased]
  command = [["rebased"]]

[build.branches]
  command = [["bin/ci.branches"]]
